[tool.poetry]
name = "render-code"
version = "0.1.0"
description = ""
authors = ["whc <249768447@qq.com>"]
readme = "README.md"
packages = [{include = "render_code"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
